/* DO NOT EDIT THIS FILE - it is machine generated */
#include "../jni.h"
/* Header for class src_ActiveWindowTracker */

#ifndef _Included_src_ActiveWindowTracker
#define _Included_src_ActiveWindowTracker
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     src_ActiveWindowTracker
 * Method:    nativeStartHook
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_src_ActiveWindowTracker_nativeStartHook
  (JNIEnv *, jobject);

/*
 * Class:     src_ActiveWindowTracker
 * Method:    nativeStopHook
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_src_ActiveWindowTracker_nativeStopHook
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
