/* DO NOT EDIT THIS FILE - it is machine generated */
#include "../jni.h"
/* Header for class src_ActiveWindow */

#ifndef _Included_src_ActiveWindow
#define _Included_src_ActiveWindow
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     src_ActiveWindow
 * Method:    getActiveWindowTitle
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_src_ActiveWindow_getActiveWindowTitle
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
