/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ActiveWindow */

#ifndef _Included_ActiveWindow
#define _Included_ActiveWindow
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ActiveWindow
 * Method:    getActiveWindowTitle
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ActiveWindow_getActiveWindowTitle
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
